apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecommerce-prod

resources:
  - ../../base
  - secret.yaml
  - service-account.yaml

patches:
  - path: patch-deployment.yaml
    target:
      kind: Deployment
      name: ecommerce-sqs
  - path: service-patch.yaml
    target:
      kind: Service
      name: ecommerce-sqs

configMapGenerator:
  - name: app-config
    behavior: replace
    literals:
      - SPRING_PROFILES_ACTIVE=prod
      - AWS_REGION=eu-west-1

replicas:
  - name: ecommerce-sqs
    count: 2
