# ServiceAccount for IRSA (IAM Roles for Service Accounts)
# The annotation links this K8s SA to an AWS IAM role
# This allows pods to access SQS without hardcoded credentials
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ecommerce-sqs-sa
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::532593931086:role/ecommerce-sqs-pod-role"
