apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ecommerce-sqs.fullname" . }}-secret
stringData:
  DB_PASSWORD: {{ .Values.env.DB_PASSWORD | quote }}
  {{- if .Values.env.AWS_ACCESS_KEY_ID }}
  AWS_ACCESS_KEY_ID: {{ .Values.env.AWS_ACCESS_KEY_ID | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.env.AWS_SECRET_ACCESS_KEY | quote }}
  {{- end }}
