apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ecommerce-sqs.fullname" . }}-sa
  {{- if .Values.irsa.enabled }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.irsa.roleArn | quote }}
  {{- end }}
