replicaCount: 2
image:
  repository: 532593931086.dkr.ecr.eu-west-1.amazonaws.com/ecommerce-sqs
  tag: latest
  pullPolicy: Always
service:
  type: LoadBalancer
  port: 8082
  nodePort: null
env:
  SPRING_PROFILES_ACTIVE: prod
  DB_PASSWORD: changeme
  AWS_REGION: eu-west-1
resources:
  requests:
    memory: "512Mi"
    cpu: "500m"
  limits:
    memory: "1Gi"
    cpu: "1000m"
